# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-24 05:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='created_date',
        ),
    ]
