# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-27 22:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_remove_form_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='pref',
            field=models.CharField(max_length=200),
        ),
    ]
