# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-27 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20160427_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='partner',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
